### ISSUE TITLE
SDK is not working on Android 12

### ISSUE THREAD

**Issue by awazgyawali** [Navigine/Indoor-Positioning-Android-Mobile-SDK#46]
**Describe the bug**
We have an app that uses the SDK for indoor positioning. It works well on the android version <11 however if we fireup the app on android 12, it doesn't work. No device info is being received. I have compileSdkVersion and targetSdkVersion set to 31.

I suspect it being a result of new location permission model (precise and approximate).

**Comment by PavelTychinin** [comment]
Hi. Thanks for your reply. We've updated SDK and Demo app. Can you check it now?
